/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32f4xx.h"
#include "fpu_init.h"
#include "usart.h"
#include "FreeRTOS.h"
#include "task.h"

int main(void)
{
  FPU_Init();
  USART2_Init();
  GPS_USART6_Init();

  USART2_Task_Init();
  vTaskStartScheduler();

  while(1){}

}
